[package]
name = "modmath"
version = "0.1.1"
edition = "2021"
description = """
Modular math implemented with traits.
"""
repository = "https://github.com/kaidokert/modmath-rs"
readme = "../README.md"
authors = ["kaidokert <kaidokert@gmail.com>"]
license = "Apache-2.0"
exclude = ["/.github/*"]
keywords = ["numerics", "bignum"]

[dependencies]
num-traits = { version = "0.2.19", default-features = false }

[dev-dependencies]
fixed-bigint = { version = "0.1.13" }
num-bigint = { package = "num-bigint", version = "0.4"}
# num-bigint_patched = { package = "num-bigint" , path = "../bn/num-bigint" }
num-bigint_patched = { package = "num-bigint", git = "https://github.com/kaidokert/num-bigint.git" , tag = "v0.4.6_patch" }
bnum = { version = "0.12", features = ["numtraits"] }
# bnum_patched = { package = "bnum" , path = "../bn/bnum", features = ["numtraits"] }
bnum_patched = { package = "bnum",features = ["numtraits"]  , git = "https://github.com/kaidokert/bnum.git", tag = "v0.12.1_patch" }
crypto-bigint = "0.6"
# crypto-bigint_patched = { package = "crypto-bigint", path = "../bn/crypto-bigint" }
crypto-bigint_patched = { package = "crypto-bigint", git = "https://github.com/kaidokert/crypto-bigint.git" , tag = "v0.6.1_rsa_patch_1" }
ibig = "0.3"
# ibig_patched = { package = "ibig", path = "../bn/ibig-rs" }
ibig_patched = { package = "ibig", git = "https://github.com/kaidokert/ibig-rs.git" , tag = "v0.3.6_patch" }
## Cant figure this one out
# uint = "0.10"
paste = "1"

[features]
default = ["std"]
std = []
constrained = []
basic = []
strict = []
