name: Rust

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: thumbv6m-none-eabi
          components: rustfmt, clippy
          profile: minimal
